### ISSUE TITLE
icon always shown in website view (when rendered in gitbook.com)

### ISSUE THREAD

**Issue by cntlsn** [jim-moody/gitbook-plugin-styled-blockquotes#4]
hello :)

I'm following the plugin examples here https://jim-moody.github.io/gitbook-plugin-styled-blockquotes/

by the way, whatever the markdown syntax
```
> **tip**
> Content goes here
```
or
```
> **tip-icon**
> Content goes here
```
the icon is always shown (when rendered in gitbook.com)

here the HTML rendered
```
<div class="alert alert-warning hints-alert">
  <div class="hints-icon">
    <i class="fa fa fa-file-text-o"></i>
  </div>
  <div class="hints-container">
    <p class="comments-section">
      Content goes here
      <div class="comments-icon">
        <div class="marker">+</div>
      </div>
    </p>
  </div>
</div>
<p>or</p>
<div class="alert alert-warning hints-alert">
  <div class="hints-icon">
    <i class="fa fa fa-file-text-o"></i>
  </div>
  <div class="hints-container">
    <p class="comments-section">
      Content goes here
      <div class="comments-icon">
        <div class="marker">+</div>
      </div>
    </p>
  </div>
</div>
```

**Comment by jim-moody** [comment]
Hey sorry I recently made a change that changed the syntax to have it default to having an icon. Now you need to explicitly say "no-icon" in order to have the icon hidden.

I felt like it was the more common use case to have the icon shown.

So now to get the icon to not show, use the following syntax:

```
 > **tip no-icon**
 > Content
```
